# Generated by Django 5.1.1 on 2024-09-13 16:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
